/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as TaxonomiesIndexImport } from './routes/taxonomies/index'
import { Route as TagsIndexImport } from './routes/tags/index'
import { Route as ReactionPackIndexImport } from './routes/reaction-pack/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as OrganizationsIndexImport } from './routes/organizations/index'
import { Route as MetaSchemasIndexImport } from './routes/meta-schemas/index'
import { Route as FilesIndexImport } from './routes/files/index'
import { Route as PostsIdImport } from './routes/posts/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const TaxonomiesIndexRoute = TaxonomiesIndexImport.update({
  path: '/taxonomies/',
  getParentRoute: () => rootRoute,
} as any)

const TagsIndexRoute = TagsIndexImport.update({
  path: '/tags/',
  getParentRoute: () => rootRoute,
} as any)

const ReactionPackIndexRoute = ReactionPackIndexImport.update({
  path: '/reaction-pack/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationsIndexRoute = OrganizationsIndexImport.update({
  path: '/organizations/',
  getParentRoute: () => rootRoute,
} as any)

const MetaSchemasIndexRoute = MetaSchemasIndexImport.update({
  path: '/meta-schemas/',
  getParentRoute: () => rootRoute,
} as any)

const FilesIndexRoute = FilesIndexImport.update({
  path: '/files/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIdRoute = PostsIdImport.update({
  path: '/posts/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdImport
      parentRoute: typeof rootRoute
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesIndexImport
      parentRoute: typeof rootRoute
    }
    '/meta-schemas/': {
      id: '/meta-schemas/'
      path: '/meta-schemas'
      fullPath: '/meta-schemas'
      preLoaderRoute: typeof MetaSchemasIndexImport
      parentRoute: typeof rootRoute
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/reaction-pack/': {
      id: '/reaction-pack/'
      path: '/reaction-pack'
      fullPath: '/reaction-pack'
      preLoaderRoute: typeof ReactionPackIndexImport
      parentRoute: typeof rootRoute
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsIndexImport
      parentRoute: typeof rootRoute
    }
    '/taxonomies/': {
      id: '/taxonomies/'
      path: '/taxonomies'
      fullPath: '/taxonomies'
      preLoaderRoute: typeof TaxonomiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PostsIdRoute,
  FilesIndexRoute,
  MetaSchemasIndexRoute,
  OrganizationsIndexRoute,
  PostsIndexRoute,
  ReactionPackIndexRoute,
  TagsIndexRoute,
  TaxonomiesIndexRoute,
  UsersIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/$id",
        "/files/",
        "/meta-schemas/",
        "/organizations/",
        "/posts/",
        "/reaction-pack/",
        "/tags/",
        "/taxonomies/",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/$id": {
      "filePath": "posts/$id.tsx"
    },
    "/files/": {
      "filePath": "files/index.tsx"
    },
    "/meta-schemas/": {
      "filePath": "meta-schemas/index.tsx"
    },
    "/organizations/": {
      "filePath": "organizations/index.tsx"
    },
    "/posts/": {
      "filePath": "posts/index.tsx"
    },
    "/reaction-pack/": {
      "filePath": "reaction-pack/index.tsx"
    },
    "/tags/": {
      "filePath": "tags/index.tsx"
    },
    "/taxonomies/": {
      "filePath": "taxonomies/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
